Create notify.yaml
c-road/git-cms-test pull request #5
Opened 2023-05-02 04:14 UTC by yas-ako

2023-05-03 13:56 UTC, c-road submitted a review, later dismissed
asdfasdf

2023-05-03 14:16 UTC, c-road submitted a review, later dismissed
あｓｄふぁｓｄあｓｄふぁｓｄｆ

2023-05-03 15:06 UTC, yas-ako commented
コメントコメント

2023-05-03 15:28 UTC, yas-ako commented
ooooooooooooooooooo

2023-05-03 15:30 UTC, yas-ako commented
kkkkkkkkkkkkk

2023-05-03 15:41 UTC, yas-ako reviewed
oooooooooooooo

2023-05-03 15:41 UTC, yas-ako commented on .github/workflows/notify.yaml
> +  # pull_request_target:
- [x] こめんと、消してもよくない？

2023-05-04 10:44 UTC, yas-ako commented
おおお

2023-05-04 10:44 UTC, yas-ako commented
おおお

2023-05-04 10:51 UTC, yas-ako reviewed
っfycうcう

2023-05-05 00:06 UTC, yas-ako commented
Asss

2023-05-05 00:06 UTC, yas-ako commented
Iooo

2023-05-05 10:24 UTC, c-road requested changes, later dismissed
あｓｄふぁｓｄｆ

2023-05-06 04:13 UTC, c-road requested changes
あｓｄふぁｓｄ

2023-05-06 05:15 UTC, c-road approved these changes
OK　OK

2023-05-06 05:15 UTC, merged